//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangMan.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HangMan.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;1,ANCESTOR,FOREFATHER (SYNONYM),(NOUN)&quot;
        ///&quot;2,BROADCAST,SEND IN ALL DIRECTIONS (SYNONYM),(NOUN)&quot;
        ///&quot;3,CHAMPION,OVERALL WINNER (SYNONYM),(NOUN)&quot;
        ///&quot;4,DESIGNATE,TO ASSIGN (SYNONYM),(NOUN)&quot;
        ///&quot;5,ESTIMATE,APPROXIMATION (SYNONYM),(NOUN)&quot;
        ///&quot;6,FRIGHTEN,MAKE AFRAID (SYNONYM),(NOUN)&quot;
        ///&quot;7,GUARANTEE,AN ASSURANCE (SYNONYM),(NOUN)&quot;
        ///&quot;8,INCREASE,TO MAKE GREATER (SYNONYM),(NOUN)&quot;
        ///&quot;9,EXCELLENT,OF HIGHEST QUALITY (SYNONYM),(NOUN)&quot;
        ///&quot;10,DISAPPEAR,TO BECOME INVISIBLE (SYNONYM),(NOUN)&quot;
        ///&quot;11,LANDLORD,TENANT (ANTONYM),(NOUN)&quot;
        ///&quot;12, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Eng_Difficult {
            get {
                return ResourceManager.GetString("Eng_Difficult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;1,AFRAID,TO FEAR (SYNONYM),(NOUN)&quot;
        ///&quot;2,BRIEF,OF SHORT TIME (SYNONYM),(NOUN)&quot;
        ///&quot;3,CHASE,GO AFTER (SYNONYM),(NOUN)&quot;
        ///&quot;4,EXIST,STATE OF BEING (SYNONYM),(NOUN)&quot;
        ///&quot;5,FAULT,A DEFECT (SYNONYM),(NOUN)&quot;
        ///&quot;6,LUNCH,MEAL DURING DAY (SYNONYM),(NOUN)&quot;
        ///&quot;7,OFTEN,FREQUENCY (SYNONYM),(NOUN)&quot;
        ///&quot;8,MERCY,SHOWING KINDNESS (SYNONYM),(NOUN)&quot;
        ///&quot;9,HUGE,VERY BIG (SYNONYM),(NOUN)&quot;
        ///&quot;10,GRANT,TO GIVE (SYNONYM),(NOUN)&quot;
        ///&quot;11,QUIET,NOISY (ANTONYM),(NOUN)&quot;
        ///&quot;12,MINOR,MAJOR (ANTONYM),(NOUN)&quot;
        ///&quot;13,GRANT,REFUSE (ANTONYM),(NOUN)&quot;
        ///&quot;14,BROAD, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Eng_Easy {
            get {
                return ResourceManager.GetString("Eng_Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;1,ACROSS,OPPOSITE SIDE (SYNONYM),(NOUN)&quot;
        ///&quot;2,DEFEAT,LOSS (SYNONYM),(NOUN)&quot;
        ///&quot;3,JEALOUS,ENVY (SYNONYM),(NOUN)&quot;
        ///&quot;4,EXPAND,INCREASE (SYNONYM),(NOUN)&quot;
        ///&quot;5,FORBID,PROHIBIT (SYNONYM),(NOUN)&quot;
        ///&quot;6,HOLLOW,UNFILLED SPACE (SYNONYM),(NOUN)&quot;
        ///&quot;7,JACKET,COAT (SYNONYM),(NOUN)&quot;
        ///&quot;8,MILLION,1000000 (SYNONYM),(NOUN)&quot;
        ///&quot;9,MYSTERY,PUZZLE (SYNONYM),(NOUN)&quot;
        ///&quot;10,LITTLE,SMALL (SYNONYM),(NOUN)&quot;
        ///&quot;11,BITTER,SWEET (ANTONYM),(NOUN)&quot;
        ///&quot;12,FAMOUS,UNKNOWN (ANTONYM),(NOUN)&quot;
        ///&quot;13,GENTLE,ROUGH (ANTONYM),(NOUN)&quot;
        ///&quot;14,HUMBLE,PROUD (ANTONYM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Eng_Medium {
            get {
                return ResourceManager.GetString("Eng_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hangman1 {
            get {
                object obj = ResourceManager.GetObject("hangman1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hangman2 {
            get {
                object obj = ResourceManager.GetObject("hangman2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hangman3 {
            get {
                object obj = ResourceManager.GetObject("hangman3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hangman4 {
            get {
                object obj = ResourceManager.GetObject("hangman4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hangman5 {
            get {
                object obj = ResourceManager.GetObject("hangman5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hangman6 {
            get {
                object obj = ResourceManager.GetObject("hangman6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hangman7 {
            get {
                object obj = ResourceManager.GetObject("hangman7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;1,TORTOISE,ANIMAL,(NOUN)&quot;
        ///&quot;2,CROCODILE,ANIMAL,(NOUN)&quot;
        ///&quot;3,ELEPHANT,ANIMAL,(NOUN)&quot;
        ///&quot;4,KANGAROO,ANIMAL,(NOUN)&quot;
        ///&quot;5,RHINOCEROS,ANIMAL,(NOUN)&quot;
        ///&quot;6,STRAWBERRY,FRUIT,(NOUN)&quot;
        ///&quot;7,PINEAPPLE,FRUIT,(NOUN)&quot;
        ///&quot;8,RASPBERRY,FRUIT,(NOUN)&quot;
        ///&quot;9,ZUCCHINI,VEGETABLE,(NOUN)&quot;
        ///&quot;10,CUCUMBER,VEGETABLE,(NOUN)&quot;
        ///&quot;11,BROCCOLI,VEGETABLE,(NOUN)&quot;
        ///&quot;12,MUSHROOM,VEGETABLE,(NOUN)&quot;
        ///&quot;13,ASPARAGUS,VEGETABLE,(NOUN)&quot;
        ///&quot;14,CAPSICUM,VEGETABLE,(NOUN)&quot;
        ///&quot;15,AEROPLANE,VEHICLE,(NOUN)&quot;
        ///&quot;16,AMBULANCE,VEHICLE,(NOUN)&quot;
        ///&quot;17,HELICOPTER,VEHICLE,(NOUN)&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Non_Eng_Difficult {
            get {
                return ResourceManager.GetString("Non_Eng_Difficult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;1,MANGO,FRUIT,(NOUN)&quot;
        ///&quot;2,APPLE,FRUIT,(NOUN)&quot;
        ///&quot;3,GRAPE,FRUIT,(NOUN)&quot;
        ///&quot;4,KIWI,FRUIT,(NOUN)&quot;
        ///&quot;5,PLUM,FRUIT,(NOUN)&quot;
        ///&quot;6,CHAIR,FURNITURE,(NOUN)&quot;
        ///&quot;7,TABLE,FURNITURE,(NOUN)&quot;
        ///&quot;8,DESK,FURNITURE,(NOUN)&quot;
        ///&quot;9,SHELF,FURNITURE,(NOUN)&quot;
        ///&quot;10,SOFA,FURNITURE,(NOUN)&quot;
        ///&quot;11,PEAS,VEGETABLE,(NOUN)&quot;
        ///&quot;12,ONION,VEGETABLE,(NOUN)&quot;
        ///&quot;13,BEANS,VEGETABLE,(NOUN)&quot;
        ///&quot;14,CRESS,VEGETABLE,(NOUN)&quot;
        ///&quot;15,OKRA,VEGETABLE,(NOUN)&quot;
        ///&quot;16,CUBE,SHAPE,(NOUN)&quot;
        ///&quot;17,CONE,SHAPE,(NOUN)&quot;
        ///&quot;18,OVAL,SHAPE,(NOUN)&quot;
        ///&quot;19,STAR,SHAPE,(NOUN)&quot;
        ///&quot;20,PRISM,SHAPE, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Non_Eng_Easy {
            get {
                return ResourceManager.GetString("Non_Eng_Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;1,NEPHEW,RELATION,(NOUN)&quot;
        ///&quot;2,SPOUSE,RELATION,(NOUN)&quot;
        ///&quot;3,SIBLING,RELATION,(NOUN)&quot;
        ///&quot;4,COUSIN,RELATION,(NOUN)&quot;
        ///&quot;5,HUSBAND,RELATION,(NOUN)&quot;
        ///&quot;6,TULIPS,FLOWER,(NOUN)&quot;
        ///&quot;7,JASMINE,FLOWER,(NOUN)&quot;
        ///&quot;8,MARIGOLD,FLOWER,(NOUN)&quot;
        ///&quot;9,DAHLIA,FLOWER,(NOUN)&quot;
        ///&quot;10,ORCHID,FLOWER,(NOUN)&quot;
        ///&quot;11,BICYCLE,VEHICLE,(NOUN)&quot;
        ///&quot;12,SCOOTER,VEHICLE,(NOUN)&quot;
        ///&quot;13,TRACTOR,VEHICLE,(NOUN)&quot;
        ///&quot;14,GLIDER,VEHICLE,(NOUN)&quot;
        ///&quot;15,ROCKET,VEHICLE,(NOUN)&quot;
        ///&quot;16,KIDNEY,BODY PART,(NOUN)&quot;
        ///&quot;17,FINGER,BODY PART,(NOUN)&quot;
        ///&quot;18,STOMACH,BODY PART,(NOUN)&quot;
        ///&quot;1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Non_Eng_Medium {
            get {
                return ResourceManager.GetString("Non_Eng_Medium", resourceCulture);
            }
        }
    }
}
